name: Deploy to k3s

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubectl only
        run: |
          curl -LO https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
          chmod +x kubectl
          ./kubectl version --client
  
      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_SECRET }}" | base64 -d > ~/.kube/config
          kubectl config set-cluster default --server=https://3.0.102.234:6443
          kubectl config set-cluster default --insecure-skip-tls-verify=true

      - name: Apply Kubernetes manifests
        run: kubectl apply -f nginx-deployment.yaml --validate=false
