name: Deploy to k3s

on:
  push:
    branches:
      - main  # or "master", depending on your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_SECRET }}" | base64 -d > ~/.kube/config
          kubectl config set-cluster default --server=https://<YOUR_CLUSTER_IP>:6443
          # Optional if self-signed cert:
          kubectl config set-cluster default --insecure-skip-tls-verify=true

      - name: Apply Kubernetes manifests
        run: kubectl apply -f nginx-deployment.yaml --validate=false
